import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Navbar from '@/components/Navbar'

import Providers from './Providers'
import './globals.css'
import SearchBox from '@/components/SearchBox'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IMDb Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body className={inter.className}>
        <Providers>
         <Header/>
         <Navbar/>
         <SearchBox/>
         {children}
        </Providers>
      </body>
    </html>
  )
}
